Repository amykarnaze/FitLit2Legit2Quit, pull requests merged in 2020-07, with the labels that each got.

#12 Test refactor
  src/User.js
  src/UserRepository.js
  src/scripts.js
  test/Activity-test.js
  test/Sleep-test.js
  test/User-test.js
  test/UserRepository-test.js
Labels: Ben, Review

#13 Add breaks between methods
  src/Activity.js
  src/Hydration.js
  src/Sleep.js
  src/User.js
  src/UserRepository.js
  src/scripts.js
Labels: Ben, Review

#17 change for loops to forEach iterators in User
  src/User.js
Labels: Ben, enhancement

#25 Add data chain into fetch function
  src/api.js
Labels: Ben, enhancement

#36 Add extend phrase to buttons in styles
  src/css/styles.scss
Labels: Ben, Styling, sass

#47 Add button and drop down menu for adding user instances
  README.md
  src/css/styles.scss
  src/images/plus-icon.png
  src/index.html
  src/scripts.js
Labels: Styling, Taryn, enhancement

#46 Add aria labels to buttons #34
  package-lock.json
  package.json
  src/index.html
Labels: Amy, Partial, accessibility, enhancement

#54 Style/bm/sass
  src/css/_body.scss
  src/css/_buttons.scss
  src/css/_text.scss
  src/css/base.scss
  src/css/styles.scss
Labels: Ben, Styling, sass

#55 Styling/rename dom
  src/index.html
Labels: Styling

#56 Create modal window for user's to make new instances of activity, sleep, and hydration
  src/css/styles.scss
  src/index.html
  src/scripts.js
Labels: Taryn, enhancement

#50 Add additional aria labels and english language
  src/index.html
Labels: accessibility, enhancement

#61 Style/bm/modal partial
  src/css/_modals.scss
  src/css/styles.scss
Labels: Ben, Styling, sass

#62 Random fixes/refactoring
  src/scripts.js
Labels: Refactor, Taryn

#73 Add moment.js and remove date section from modal
  package-lock.json
  package.json
  src/css/_modals.scss
  src/index.html
  src/scripts.js
Labels: Taryn, dependencies, enhancement

#77 Collect User Input
  src/css/_modals.scss
  src/index.html
  src/scripts.js
Labels: Taryn, enhancement

#78 Test/bm/spies
  src/scripts.js
  src/singleDomFunction.js
  test/scripts-test.js
Labels: Ben, Partial, Test cases, invalid

#82 Api/ak/resolvepromise
  src/api.js
  src/scripts.js
Labels: Amy, Refactor, api, enhancement

#79 Feature/tm/collect user input
  src/index.html
  src/scripts.js
Labels: Taryn, enhancement

#86 Refactor/scripts #85 #89
  src/scripts.js
Labels: Amy, Refactor

#88 Feature/bm/alert box script
  src/scripts.js
Labels: Ben, enhancement

#98 Refactor Icons for Buttons/Adjust colors for accessiblity
  README.md
  src/css/_buttons.scss
  src/css/_variables.scss
  src/images/calendar.png
  src/images/group.png
  src/images/information.png
  src/images/line-chart.png
  src/images/return.png
  src/index.html
  src/scripts.js
Labels: Taryn, accessibility, sass

#99 Postdata/ak/setup
  package-lock.json
  src/api.js
  src/scripts.js
Labels: Amy, Review, api, question

#103 Bm/styling/submission forms
  src/api.js
  src/css/_buttons.scss
  src/css/_modals.scss
  src/index.html
  src/scripts.js
Labels: Ben, Styling, enhancement, sass

#91 Refactor/inheritance: User update action methods
  old-userTest-and-UserClass.js
  src/Activity.js
  src/User.js
Labels: Hanna, Refactor

#102 Refactor/hk/classes: weekly average User calculations
  old-userTest-and-UserClass.js
  src/Activity.js
  src/User.js
  src/UserRepository.js
  src/scripts.js
  test/User-test.js
  test/UserRepository-test.js
Labels: Refactor, Test cases

#105 Add Accessiblity
  src/css/styles.scss
  src/index.html
  src/scripts.js
Labels: Taryn, accessibility

#104 Add media query and refactor scss
  src/css/_buttons.scss
  src/css/_instance-dropdown.scss
  src/css/_media-queries.scss
  src/css/_modals.scss
  src/css/styles.scss
  src/images/user.png
  src/index.html
  src/scripts.js
Labels: Styling, Taryn, accessibility, enhancement, sass

#107 Refactor buttons in adding instances
  src/css/_buttons.scss
  src/css/_instance-dropdown.scss
  src/css/styles.scss
Labels: Refactor, Styling, Taryn, accessibility, sass

#112 Refactor/Bug Issue
  src/Activity.js
  src/Hydration.js
  src/User.js
  src/UserAction.js
  src/api.js
  src/scripts.js
  src/singleDomFunction.js
  test/Hydration-test.js
  test/Sleep-test.js
  test/User-test.js
  test/scripts-test.js
Labels: Partial, Taryn, bug

#114 Fix Bug that wouldn't display data from server
  src/User.js
  src/UserRepository.js
  src/scripts.js
Labels: Partial, Refactor, Taryn, bug

#115 Style/bm/fix alert box
  src/css/_instance-dropdown.scss
  src/css/_media-queries.scss
  src/css/_modals.scss
  src/index.html
  src/scripts.js
Labels: Ben, Styling, sass

#119 Bugfixes/bm/small fixes
  src/css/_media-queries.scss
  src/scripts.js
Labels: Ben, Styling, sass

#120 fix the modal alert to show the alert message
  src/scripts.js
Labels: Ben, enhancement
